### ISSUE TITLE
Feat: Implement `GetSQLQuery` method

### ISSUE THREAD

**Issue by Shivansh-yadav13** [Shivansh-yadav13/SQLite-UI#14]
**We need to display the query using which the same table can be created.**

- Implement the method here:
https://github.com/Shivansh-yadav13/SQLite-UI/blob/c4a0df28e6178ca77801dbb46eae88b14acba9fb/db/database.go#L89

- We are receiving the result here:
https://github.com/Shivansh-yadav13/SQLite-UI/blob/c4a0df28e6178ca77801dbb46eae88b14acba9fb/routes/handlers.go#L24

- Display the value here:
https://github.com/Shivansh-yadav13/SQLite-UI/blob/c4a0df28e6178ca77801dbb46eae88b14acba9fb/templates/table_view.html#L11

Execute the query as done in the `GetTables()` method.

**Comment by wliao008** [comment]
@Shivansh-yadav13 im looking for an interesting project to do hacktoberfest and i've always been on the lookout for an easier way to manage my sqlite db, so i'd be happy to help out! for this issue can you elaborate a bit what you have in mind? is it doing a `select *` against a table and returning the result?

**Comment by Shivansh-yadav13** [comment]
@wliao008 Thankyou :heart:  for showing interest in this project, my aim for this project is to make this an alternative for the software [DB Browser for SQLite](https://sqlitebrowser.org/) and any suggestion from your side is welcomed for better development.

Since we have options to create/delete a table, now I'm planning to add features to edit/delete/add more columns to the table and show all the specifications like type of data that can be stored in the column or if column can be null or not etc.

This issue is to show the sql query used to create the table, which will automatically update when modifying the table.
like for creating the table we use `CREATE TABLE tablename('id' INTEGER NOT NULL PRIMARY KEY)`
but this feature is not priority rn and can be done later. 

you can also checkout this issue https://github.com/Shivansh-yadav13/SQLite-UI/issues/16

**Comment by wliao008** [comment]
Ah I see, you want the table schema. 👍
