### ISSUE TITLE
[Feature] Add option for adding columns to the table

### ISSUE THREAD

**Issue by Shivansh-yadav13** [Shivansh-yadav13/SQLite-UI#16]
Create a form on [templates/table_view.html](https://github.com/Shivansh-yadav13/SQLite-UI/blob/main/templates/table_view.html) which will send a post request to a route which will add a column to a particular table.
The form should also have options available when adding columns like `Primary Key`, `DataType`, `Not null` etc.
The name of the table can be taken from the url params.

steps:
- Create a method for the above task on the [db](https://github.com/Shivansh-yadav13/SQLite-UI/tree/main/db) package.
- Then create a handler in the [routes](https://github.com/Shivansh-yadav13/SQLite-UI/tree/main/routes) package which will call method from the db package.
- Create a [route](https://github.com/Shivansh-yadav13/SQLite-UI/blob/main/routes/routes.go) for the above handler.
- Create form on [templates/table_view.html](https://github.com/Shivansh-yadav13/SQLite-UI/blob/main/templates/table_view.html) and send the post request to the above route.

**Comment by VanTekken** [comment]
Please assign this issue to me 🥷

**Comment by Shivansh-yadav13** [comment]
@VanTekken assigned :+1:
