### ISSUE TITLE
[Test] Add unit test for `AddColumn`

### ISSUE THREAD

**Issue by Shivansh-yadav13** [Shivansh-yadav13/SQLite-UI#21]
- add unit test for `AddColumn` method in `db` package.
- https://github.com/Shivansh-yadav13/SQLite-UI/blob/ade5d4242b42a040c51897cddb96e2f56feae01d/db/database.go#L100

**Comment by MagnaibayarMN** [comment]
Hello? Can I contribute it?

**Comment by Shivansh-yadav13** [comment]
@MagnaibayarMN yes, assigned :+1:

**Comment by MagnaibayarMN** [comment]
@Shivansh-yadav13 Sir please check this [PR](https://github.com/Shivansh-yadav13/SQLite-UI/pull/25) that I created as a draft.
And please advise me for how to pass semantic PR

**Comment by Shivansh-yadav13** [comment]
@MagnaibayarMN Replied the PR 😅 no need to address as sir, I'm just a student.
