### ISSUE TITLE
Switch to a smaller base docker image

### ISSUE THREAD

**Issue by wliao008** [Shivansh-yadav13/SQLite-UI#23]
The current docker image is base off `golang:1.18`, which is 900+mb when pulled down. It's not needed to run the actual end program.

There are 2 ways that this can be approached:

1. Use a 2 step build process: build the app in the golang container, then copy the resulting binary onto a smaller image, all done via the Dockerfile.
2. Build the app outside of the container, maybe via a Makefile, and copy the resulting binary to a smaller image.

Alpine is a pretty good choice, this'd cut the size down from 900+mb to around ~20mb.

**Comment by wliao008** [comment]
@Shivansh-yadav13 i can work on this if you assign it to me, probably will take the first option.

**Comment by Shivansh-yadav13** [comment]
sure @wliao008 assigned :+1:
