### ISSUE TITLE
Front end layout 

### ISSUE THREAD

**Issue by wliao008** [Shivansh-yadav13/SQLite-UI#28]
As discussed in #6, incorporate tailwindcss and setup a dashboard style structure for the app.

**Comment by Aahil13** [comment]
Good day @wliao008. I love this project.
I would love to be assigned this as I can handle this, but I would need a template.
Please could you point me to a webpage that suits what you desire for the dashboard, or maybe a low-fidelity design of what you want?
With that, I can be assigned and would start working on it

**Comment by wliao008** [comment]
@Aahil13 that is awesome! I don't have permission to assign issue, but @Shivansh-yadav13 can. 

The style that I think we're looking for is this: https://tailwindui.com/components/application-ui/application-shells/sidebar, where the left panel would be navigation menus (in this case it'd contain list of db tables etc).

**Comment by Shivansh-yadav13** [comment]
@Aahil13 you can create a basic dashboard rn, I'll work on to create a figma design for future pages and features we will have and, then we will update the frontend.

**Comment by johnhorsema** [comment]
@Shivansh-yadav13 I have just added tailwindcss and revamped the home page. Submitted the pull request here: #36.
