### ISSUE TITLE
[BUG] prevent creation of tables with no names

### ISSUE THREAD

**Issue by Shivansh-yadav13** [Shivansh-yadav13/SQLite-UI#30]
**Describe the bug**
Create table method can create a table without any name

**Expected behavior**
table-name field cannot be empty when clicking on `Create` table button.

**Screenshots**
![Screenshot from 2022-10-19 10-57-23](https://user-images.githubusercontent.com/87603425/196604836-b488dfd0-7143-4a42-910b-7b7ec9e22959.png)

**Comment by RachitGarg-12** [comment]
@Shivansh-yadav13  i would like to contribute on this issue.

**Comment by RachitGarg-12** [comment]
@Shivansh-yadav13  i am not able to to run "go run main.go"  command , could u help me setting up.

**Comment by Shivansh-yadav13** [comment]
@RachitGarg-12 what does the terminal says? and are you following the setup guide https://github.com/Shivansh-yadav13/SQLite-UI#-set-up-project-locally
