### ISSUE TITLE
[feat]: de-duplicate the layout

### ISSUE THREAD

**Issue by wliao008** [Shivansh-yadav13/SQLite-UI#42]
The current layout is duplicated across all the pages, which is not ideal if a change is needed.

Break the layout into different templates so the layout can be "composed". The desired outcome of this, is that a new page should be self-contained.

Our current layout structure is pretty simple, mainly a left nav and a right content area. I can see something like this:

```
{{ define "header" }}
  ... all the header + nav element here ...
{{ end }}
```

```
{{ define "footer" }}
  ... all the footer element here ...
{{ end }}
```

Then in any given page, for ex when viewing the table data:
```
{{ template "header" . }}
... the actual data specific to this page ...
{{ template "footer" . }}
```

**Comment by johnhorsema** [comment]
We need to use a templating engine on the server side in order to render partial layouts across different pages.
@wliao008 I'm not that familiar with Go, but is the below the best for this project, since we already use Fiber.

https://github.com/gofiber/template

**Comment by johnhorsema** [comment]
@wliao008 let's use this https://github.com/gofiber/template/tree/master/html
It says there is [embed.FS](https://github.com/gofiber/template/tree/master/html#example-with-embedfs), what does it mean compared to the basic example provided at the top?

**Comment by wliao008** [comment]
@johnhorsema sounds good. embed.fs just mean the assets are embedded into the end program, vs pulling in the assets at run time.
